### ISSUE TITLE
Question: Is there any method where I can pass a bundle directly?

### ISSUE THREAD

**Issue by PrashamTrivedi** [robertoestivill/intentbuilder#4]
Like extra() where one can pass key and value, is there any method where I can pass a bundle directly to add in the extras? If yes, it's better to update the documentations.

**Comment by robertoestivill** [comment]
@PrashamTrivedi Yes there is. 

https://github.com/robertoestivill/intentbuilder/blob/master/intentbuilder%2Fsrc%2Fmain%2Fjava%2Fintentbuilder%2FIntentBuilder.java#L134-L138

``` java
    public IntentBuilder extras(Bundle extras) {
        validateNotNull(extras, "Extras bundle");
        mIntent.putExtras(extras);
        return this;
    }
```

The `IntentBuilder` class has methods for all the `Intent` original methods ~~( except the ones listed on https://github.com/robertoestivill/intentbuilder/issues/2 )~~

Putting examples of all the different methods on the README will clutter it. 
Do you have any ideas? Maybe a wiki page? Pull requests are always welcome :)

**Comment by robertoestivill** [comment]
Closing as the functionality is already implemented.
