### ISSUE TITLE
You might be interested in

### ISSUE THREAD

**Issue by stephanenicolas** [robertoestivill/intentbuilder#5]
https://github.com/f2prateek/dart/pull/33

We are doing more or less the same thing with Dart. Our implementation has some features you don't have (extra injection, easy parcelables). Maybe you would like to contribute to Dart ?

**Comment by robertoestivill** [comment]
Nicee, I will take a look at it. Thanks for the heads up

**Comment by robertoestivill** [comment]
@macarse @stephanenicolas  -> @emilsjolander is working on something similar in regards to intent extras injection

https://github.com/emilsjolander/IntentBuilder
