### ISSUE TITLE
Intent Categories are not supported

### ISSUE THREAD

**Issue by Gibolt** [robertoestivill/intentbuilder#6]
The code below launches the home screen. Would be nice if it was easy to add a category with the builder
```java
Intent intent = new Intent(Intent.ACTION_MAIN);
intent.addCategory(Intent.CATEGORY_HOME);
```

**Comment by robertoestivill** [comment]
Thanks for the feedback.

PR https://github.com/robertoestivill/intentbuilder/pull/7 adds support for categories as a varargs method.

`0.1.2` has been pushed to maven repository
